name: Format Code with Prettier

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Run Prettier Check
      run: npx prettier --check .

    - name: Run Prettier to Fix Formatting
      run: |
        npx prettier --write .
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "chore: format code with Prettier" || echo "Nothing to commit"
        git push || echo "No changes to push"
